name: Build and Publish Flutter Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: image-flutter

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Transforme le nom du dépôt en minuscules pour Docker
      - name: Lowercase repo name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}-flutter" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Syntaxe corrigée ici
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
